### ISSUE TITLE
Threshold value for custom apps

### ISSUE THREAD

**Issue by dhcgn** [dhcgn/go-mqtt-dispatcher#4]
Use this config
```yaml
    ignore:
      lessThan: 2.0
```

Whole Config:
```yaml
mqtt:
  broker: mqtt://192.168.1.10:1883

topics:
  - subscribe: "shellies/shellypro3em-0000000/status/em:0"
    ignore:
       lessThan: 2.0
    transform:
      jsonPath: "$.total_act_power"
      outputFormat: "%.0f W"
    publish: "awtrix_b77810/custom/house power"
    icon: "redplug"
topics_accumulated:
  - Gruop: "Solar"
    publish: "awtrix_000000/custom/solar power"
    icon: "ani_sun"
    operation: sum
    outputFormat: "%.0f W"
    ignore:
      lessThan: 2.0
    topics:
      - subscribe: "shellies/shellypro4pm-0000000000/status/switch:2"
        transform:
          jsonPath: "$.apower"
          invert: true
      - subscribe: "shellies/shellyplusplugs-0000000000/status/switch:0"
        transform:
          jsonPath: "$.apower"
```
